use_frameworks!

platform :ios, '9.0'

target 'ReactNativeBridgeInstrument_Example' do
  pod 'ReactNativeBridgeInstrument', :path => '../'

  target 'ReactNativeBridgeInstrument_Tests' do
    inherit! :search_paths

    
  end
end
