# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'ReactNativeBridgeInstrument' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeBridgeInstrument
  pod 'React-Core', :git => 'git@github.com:facebook/react-native.git'

end
